blog/urls.py
from django.urls import path, include

from .views import (
    PostListView, PostDetailView, SignUpView, CommentaryCreateView,
    PostCreateView, PostUpdateView, PostDeleteView,
    MyPostsListView, about_view
)

urlpatterns = [
    path("", PostListView.as_view(), name="index"),
    path("my-posts/", MyPostsListView.as_view(), name="my-posts"),
    path("posts/<int:pk>", PostDetailView.as_view(), name="post-detail"),
    path(
        "posts/<int:pk>/update", PostUpdateView.as_view(), name="post-update"
    ),
    path(
        "posts/<int:pk>/delete", PostDeleteView.as_view(), name="post-delete"
    ),
    path(
        "posts/<int:pk>/post-comment",
        CommentaryCreateView.as_view(), name="commentary-create"
    ),
    path("posts/create", PostCreateView.as_view(), name="post-create"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/sign-up/", SignUpView.as_view(), name="sign-up"),
    path("about/", about_view, name="about")
]

app_name = "blog"

blog_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Post(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=500)
    created_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_time"]

    def __str__(self):
        return f'{self.owner.first_name} {self.owner.last_name} "{self.title}"'


class Commentary(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now=True)
    content = models.TextField(max_length=500)

    class Meta:
        verbose_name_plural = "commentaries"
        ordering = ["-created_time"]

    def __str__(self):
        return (
            f'{self.user.first_name} {self.user.last_name}: "{self.content}"'
        )

blog/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import Textarea
from django.forms.models import ModelForm

from blog.models import Commentary, Post


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "email")


class CommentaryForm(ModelForm):
    class Meta:
        model = Commentary
        fields = ("content",)
        labels = {"content": "Post a comment", }
        widgets = {"content": Textarea(attrs={"cols": 20, "rows": 3}), }


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ("title", "content",)

blog/views.py
from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import (
    PermissionRequiredMixin, LoginRequiredMixin
)
from django.core.paginator import Paginator
from django.http import HttpRequest
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.views import generic

from blog.forms import CustomUserCreationForm, CommentaryForm, PostForm
from blog.models import Post, Commentary


class PostListView(generic.ListView):
    model = Post
    queryset = (
        Post.objects.select_related("owner").prefetch_related("commentary_set")
    )
    template_name = "blog/index.html"
    paginate_by = 5


class MyPostsListView(LoginRequiredMixin, generic.ListView):
    model = Post
    template_name = "blog/index.html"
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.select_related(
            "owner"
        ).prefetch_related("commentary_set").filter(owner=self.request.user)


class PostDetailView(generic.DetailView):
    model = Post

    def get_queryset(self):
        return Post.objects.select_related(
            "owner"
        ).prefetch_related("commentary_set__user")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = self.get_object()
        comment_list = post.commentary_set.all()
        paginator = Paginator(comment_list, 3)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        context["page_obj"] = page_obj
        context["paginator"] = paginator
        context["is_paginated"] = True
        context["form"] = CommentaryForm()
        return context


class CommentaryCreateView(generic.CreateView):
    form_class = CommentaryForm
    model = Commentary
    template_name = "blog/post_detail.html"

    def form_valid(self, form):
        form = self.form_class(self.request.POST)
        if form.is_valid():
            commentary = form.save(commit=False)
            commentary.user_id = self.request.user.id
            commentary.post_id = self.kwargs["pk"]
            commentary.save()

        return redirect("blog:post-detail", pk=self.kwargs["pk"])


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = PostForm
    model = Post

    def form_valid(self, form):
        form = self.form_class(self.request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner_id = self.request.user.id
            post.save()

        return redirect("blog:index")


class PostUpdateView(PermissionRequiredMixin, generic.UpdateView):
    form_class = PostForm
    model = Post
    success_url = reverse_lazy("blog:index")

    def has_permission(self):
        post = self.get_object()
        return post.owner == self.request.user


class PostDeleteView(PermissionRequiredMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy("blog:index")

    def has_permission(self):
        post = self.get_object()
        return post.owner == self.request.user


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    model = get_user_model()
    template_name = "registration/sign_up.html"

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)

        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse("blog:index")


def about_view(request: HttpRequest):
    return render(request, "blog/about_template.html")

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
  >
  {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'images/favicon.svg' %}">
  <title>Blog</title>
</head>
<body>
  {% block header %}
    {% include "includes/header.html" %}
  {% endblock %}

  {% block content %}{% endblock %}

  {% block pagination %}
    {% include "includes/pagination.html" %}
  {% endblock %}
</body>
</html>

templates/blog/about_template.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-center">
    <div class="w-50">
      <h2>About Django Blog App</h2>
      <p>
        Django Blog is a dynamic and user-friendly web application designed for seamless content creation
        and engagement. Built with Django, it enables users to create, edit, and delete blog posts while fostering
        interaction through a robust commenting system.
      </p>
    </div>
  </div>
{% endblock %}

templates/blog/index.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-center">
    <div class="w-50">
      {% if post_list %}
        <div class="list-group">
          {% for post in post_list %}
            <a href="{% url 'blog:post-detail' pk=post.id %}"
               class="list-group-item list-group-item-action flex-column align-items-start position-relative"
            >
              {% if post.commentary_set.count %}
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-secondary custom-badge">
                  {{ post.commentary_set.count }}
                  <span class="visually-hidden">unread messages</span>
                </span>
              {% endif %}
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 title">{{ post.title }}</h5>
                <small>{{ post.created_time }}</small>
              </div>
              <p class="mb-1">
                {{ post.owner.username }}
                {% if post.owner.first_name and post.owner.last_name %}
                  ({{ post.owner.first_name }} {{ post.owner.last_name }})
                {% endif %}
              </p>
            </a>
          {% endfor %}
        </div>
      {% else %}
        <h3>There are no posts yet... Make one right now to see it here!</h3>
      {% endif %}
      <a href="{% url 'blog:post-create' %}" class="btn btn-dark mt-3">Make a post</a>
    </div>
  </div>
{% endblock %}

templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block content %}
      <h3 class="text-center">Are you sure you want to delete the post "{{ post.title }}"?</h3>
      <form action="" method="post" class="text-center">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-outline-danger">
        <a href="{% url 'blog:post-detail' pk=post.id%}" class="btn btn-outline-secondary">Cancel</a>
      </form>
{% endblock %}

templates/blog/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="d-flex justify-content-center">
    <div class="w-50">
      <div class="d-flex align-items-center justify-content-between">
        <h2 class="mb-0">{{ post.title }}</h2>
        {% if post.owner == user %}
          <div>
            <a href="{% url 'blog:post-update' pk=post.id %}" class="btn btn-outline-primary">Update</a>
            <a href="{% url 'blog:post-delete' pk=post.id %}" class="btn btn-outline-danger">Delete</a>
          </div>
        {% endif %}
      </div>
      <small>{{ post.created_time }}</small>
      <p>{{ post.content }}</p>

      <label class="mb-2">{{ post.commentary_set.count }} comment{{ post.commentary_set.count|pluralize }}</label>
      {% for comment in page_obj %}
        <div class="list-group-item mb-3 border rounded-3">
          <div class="d-flex w-100 justify-content-between border-bottom">
            <h5 class="mb-1 title">{{ comment.user.username }}</h5>
            <small>{{ comment.created_time }}</small>
          </div>
          <p class="my-2">{{ comment.content }}</p>
        </div>
      {% endfor %}

      {% if user.is_authenticated %}
        <form action="{% url 'blog:commentary-create' pk=post.id %}" method="post" class="mt-3">
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" value="Post" class="btn btn-dark">
        </form>
      {% else %}
        <p class="text-secondary mt-3">
          You are not allowed to post comments. <a href="{% url 'blog:login' %}" class="link-dark">Login</a> to post a comment
        </p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/blog/post_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="d-flex justify-content-center">
    <div class="w-50">
      <h2>{{ object|yesno:"Update, Create" }} a post</h2>
      <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="{{ object|yesno:"Update, Create" }}" class="btn btn-dark">
      </form>
    </div>
  </div>
{% endblock %}

templates/includes/header.html
{% load static %}
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom p-4">
  <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
    <img class="bi me-2" width="45" height="45" role="img" src="{% static 'images/blog-logo.svg' %}" alt="Logo">
  </a>

  <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
    <li><a href="{% url 'blog:index' %}" class="nav-link px-2 link-dark">All Blogs</a></li>
    <li><a href="{% url 'blog:my-posts' %}" class="nav-link px-2 link-dark">My Blogs</a></li>
    <li><a href="{% url 'blog:about' %}" class="nav-link px-2 link-dark">About</a></li>
  </ul>

  <div class="col-md-3 text-end">
    {% if user.is_authenticated %}
      <span class="badge rounded-pill bg-secondary m-2 p-2">{{ user.username }}</span>
      <a href="{% url 'blog:logout' %}" class="btn btn-dark me-2">Logout</a>
    {% else %}
      <a href="{% url 'blog:login' %}" class="btn btn-outline-secondary me-2">Login</a>
      <a href="{% url 'blog:sign-up' %}" class="btn btn-dark">Sign-up</a>
    {% endif %}
  </div>
</header>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination justify-content-center mt-5">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link text-dark"> << </a>
      </li>
    {% endif %}
    <li class="page-item">
      <span class="page-link text-white bg-dark">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item ">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link text-dark"> >> </a>
      </li>
    {% endif %}
  </ul>
{% endif %}